/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b1339ba7-1b75-41f7-b038-4a0cd5b01c27",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_t67FC41iC",
    "aws_user_pools_web_client_id": "6sk6alt9l6qmfn114u4seq3tcc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://lpeokhduszfkdnzpxluaqzbzce.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "cofishapp82eb624cb91b409a9682420458a78bba03094-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
